Component
Marcraphael12/Marc-the-magician pull request #2
Opened 2021-10-29 10:02 UTC by Marcraphael12

In this PR, we are implementing a UI of the calculator App

- Delete all the boilerplate from CRA (text, images, styles)
- Don't add any extra design
- Develop just the UI of the calculator; the math logic to make it work will be added in the next project.
- Use class based components

2021-10-29 10:51 UTC, eliasecasta requested changes
# Status:  Changes Required ♻️
_Check the comments under the review_
<hr>

Hello @Marcraphael12, I am Elias, your reviewer for this PR

Well done so far with your project! Your linters are correctly set and you are using class-based functionalities for your component.js keep it up!

I will mention to you a small summary of things that need to be changed in order to keep moving:

- [x] After running npm i and start I get this error, due to it I was unable to check your design, please fix it in order to display your project correctly:

![image](https://user-images.githubusercontent.com/38522578/139421739-c9ed83cf-45ca-4faf-973a-7c4c44df3421.png)

- [x] Please add the project title to your Readme, currently, it only has the sample text provided in the template.

- [x] Please check below for extra requirements for your project.

Please correct those issues and send another review request, good luck, and well done so far! 

Code review by Elias Castañeda

_(Feel free to leave any questions or comments in the PR thread if something is not 100% clear)_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561) you have a limited number of code reviews per project (you can check the exact number in your Dashboard). If you think that the code review was not fair, you can [request a second opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-29 10:51 UTC, eliasecasta commented on src/App.js
>  function App() {
- [x] Your app.js should also be class-based, please convert it accordingly to comply with the project requirements.

2021-10-29 10:51 UTC, eliasecasta commented on src/components/component.js
> +/* eslint-disable class-methods-use-this */
- [x] Please don't disable linter rules, they are here to help you improve your code and to enforce good practices.

2021-10-29 10:51 UTC, eliasecasta commented on src/components/component.js
> +
- [x] Please rename your component.js file to something more meaningful like Calculator.js in this case, it is a little confusing because we can create a lot of components in React.

2021-10-30 10:20 UTC, Marcraphael12 commented on src/components/component.js
> +/* eslint-disable class-methods-use-this */
Thanks, but by following those best practices, I have those errors, and if I try to fix that (by removing the constructor) the app no longer works

2021-10-30 11:25 UTC, DeliceLydia approved these changes
# Congratulations🎉🎉

## Hi @Marcraphael12, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard).. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-30 11:32 UTC, merged

2022-01-04 09:29 UTC, dasileker commented
### **Hi @Marcraphael12 ,** 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has already been approved I will open a zandesk ticket

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._